## @file data_keys.py
#  @brief Делаем идентификаторы параметров из файла params.xml для станции, заданной аргументом TAKI00039-01 81 16.vsdx Python 3.7.9
#  @details
#  @date 09.03.2022
#  @author Никонов С.Ю.
#  @version 0.0.1

# Пример запуска
# /etc/Python37/python \
#     py_scripts/data_keys.py \
#     -station SES200M \
# 	  station_data/params.xml \
# 	  src/generated/data_keys.h

# Офсет идентификаторов. Предполагает, что не может быть более 300 параметров у группы (например, у агрегата)
ID_OFFSET = 300

# Импорт модулей, которые нужно устанавливать
from multiprocessing.sharedctypes import Value
import lxml.etree

# Импорт модулей встроенных в Python
import sys
import datetime
import io
import argparse
import pprint
from collections import Counter


def main():
    # Смена кодировки вывода на utf-8
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
    # Печать на экран названия текущего скрипта
    print("data_keys.py")

    # Создание парсера аргументов
    # Чтобы посмотреть какие есть аргументы, нужно запустить скрипт с параметром --help
    # Например, python event_names.py --help
    parser = argparse.ArgumentParser()
    # аргумент -station <station>
    parser.add_argument("-station")
    # аргумент <params_xml_filename> - входящий файл
    parser.add_argument("params_xml_filename", help="params.xml filename with path")
    # аргумент <out_filename> - исходящий файл
    parser.add_argument("out_filename", help="Out filename with path")
    # Парсинг аргументов
    args = parser.parse_args()

    # Станция из аргументов
    station = args.station

    # Создание пустой строки, которая работает как файл
    out_file = io.StringIO("")

    # Открытие входящего файла
    with open(args.params_xml_filename, encoding="utf-8") as f:
        xml_string = f.read()

    # Печать на экран информации о именах исходных и выходных файлов
    print(f"{args.params_xml_filename} -> {args.out_filename}")

    # Вывод первых строчек с датой и временем
    print("//AUTOGENERATED FILE, DO NOT EDIT", file=out_file)
    print(
        "// Дата и время обновления: "
        + datetime.datetime.now().strftime("%d.%m.%Y %H:%M"),
        file=out_file,
    )
    print(file=out_file)
    print("#ifndef __DATA_KEYS_HEADER__", file=out_file)
    print("#define __DATA_KEYS_HEADER__", file=out_file)
    # print(file=out_file)

    # Загрузка xml файла в парсинг XML. Библиотека lxml
    doc = lxml.etree.XML(xml_string.encode())

    # XPath для поиска unit с paramenter, event, limit
    units_xpath = f"/station/unit/*[self::parameter or self::event or self::limit]/products[1]/{station}/ancestor::unit"
    # Сам поиск units
    units = doc.xpath(units_xpath)

    # Печать на экран результатов поиска
    print(f"Найдено кол-во units={len(units)}")
    print(f"XPath для units: {units_xpath}")

    # Найденным элементам присваиваем тип unit
    unit_types = ["unit"] * len(units)

    # XPath для поиска devices с событиями
    devices_xpath = f"/station/device/*[self::parameter or self::event or self::limit]/products[1]/{station}/ancestor::device"

    # Сам поиск devices
    devices = doc.xpath(devices_xpath)

    # Печать на экран результатов поиска
    print(f"Найдено кол-во devices={len(devices)}")
    print(f"XPath для devices: {devices_xpath}")

    # Найденным элементам присваиваем тип device
    unit_types += ["device"] * len(devices)

    # Объединяем units и devices в один массив
    units += devices

    # Инициализация переменных количества событий в units и в devices
    n_unit_par_ev_lim = 0
    n_device_par_ev_lim = 0

    # Переменная, где сохраняются все global_id
    global_ids = []

    # Инициализация счётчика для кодов индентификаторов
    id_counter = 1
    for i, unit in enumerate(units):
        # Вывод названия агрегата
        print(file=out_file)
        if unit_types[i] == "unit":
            type_string = "Агрегат"
        elif unit_types[i] == "device":
            type_string = "Устройство"
        else:
            raise ValueError(
                "Неизвестный тип родителя. По дизайну этой ошибки не должно быть"
            )
        print(f'// {type_string} {unit.get("name")}', file=out_file)
        print(file=out_file)

        # Это начало идентификаторов из параметров агрегата/устройства
        start_range_unit = int(unit.get("range"))
        id_counter = start_range_unit
        # Если это агрегат, то добавляем офсет
        if unit_types[i] == "unit":
            id_counter += ID_OFFSET

        # Поиск всех параметров, событий, лимитов в агрегате / устройствах
        par_ev_lims = unit.xpath(
            f"*[self::parameter or self::event or self::limit]/products/{station}/parent::*/parent::*"
        )

        # Подсчёт кол-ва param, событий, лимитов у units и devices
        if unit_types[i] == "unit":
            n_unit_par_ev_lim += len(par_ev_lims)
        elif unit_types[i] == "device":
            n_device_par_ev_lim += len(par_ev_lims)

        # Вывод названия события в комментарии и его кода в коде программы
        for pel in par_ev_lims:
            pel_id = pel.get("common_id")
            if pel_id is None:
                pel_id = id_counter
                id_counter += 1
            print(f'// {pel.get("name")}', file=out_file)
            print(
                f'#define KEY_{pel.get("designation")} ((uint32_t)({pel_id}))',
                file=out_file,
            )
            global_ids.append(pel_id)

    print(f"Кол-во параметров, событий, лимитов у агрегатов={n_unit_par_ev_lim}")
    print(f"Кол-во параметров, событий, лимитов у устройств={n_device_par_ev_lim}")
    print(
        f"Всего кол-во параметров, событий, лимитов={n_unit_par_ev_lim + n_device_par_ev_lim}"
    )

    global_id_counts = {}
    global_id_counts_error = False
    bad_global_ids = []
    for k, v in Counter(global_ids).items():
        if v > 1:
            global_id_counts[k] = v
            global_id_counts_error = True
            bad_global_ids.append(k)

    print("global_id, которые встречаются больше одного раза:")
    pprint.pprint(global_id_counts)
    bad_global_ids_str = ", ".join(bad_global_ids)
    if global_id_counts_error:
        raise ValueError(f"Global_id=[{bad_global_ids_str}] встречаются несколько раз")

    # Печать конца файла
    print(file=out_file)
    print("#endif", file=out_file)

    # Сохраняем новый файл
    with open(args.out_filename, "w", encoding="utf-8") as f:
        print(out_file.getvalue(), file=f)


if __name__ == "__main__":
    main()
