# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout
# from PyQt5.QtCore import QCoreApplication
# import time
#
# class MyWindow(QWidget):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle("Process Events Example")
#         self.setGeometry(100, 100, 300, 200)
#
#         layout = QVBoxLayout()
#         self.button = QPushButton("Start Long Operation")
#         self.button.clicked.connect(self.start_long_operation)
#         layout.addWidget(self.button)
#         self.setLayout(layout)
#
#     def start_long_operation(self):
#         print("Starting long operation...")
#         for i in range(10):
#             print(f"Processing step {i+1}...")
#             time.sleep(0.5)  # Simulate a long-running task
#             QCoreApplication.processEvents() # Process events to keep UI responsive
#         print("Long operation finished.")
#
# if __name__ == "__main__":
#     app = QApplication([])
#     window = MyWindow()
#     window.show()
#     app.exec_()

# from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QTextEdit
# import sys
#
#
# class MyApp(QWidget):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle("Ввод текста PyQt5")
#         self.setGeometry(100, 100, 300, 200)
#
#         # Создаем виджет QTextEdit
#         self.text_input = QTextEdit(self)
#         self.text_input.setPlaceholderText("Введите текст здесь...")  # Установка текста-подсказки
#         self.text_input.textChanged.connect(self.on_text_changed)  # Подключение сигнала изменения текста
#
#         # Создаем компоновщик и добавляем виджеты
#         layout = QVBoxLayout()
#         layout.addWidget(self.text_input)
#         self.setLayout(layout)
#         return None
#
#     def on_text_changed(self):
#         # Получаем текущий текст из виджета
#         current_text = self.text_input.toPlainText()
#         print(f"Введенный текст: {current_text}")
# if __name__ == '__main__':
#     app = QApplication(sys.argv)
#     window = MyApp()
#     print(window)
#     window.show()
#     sys.exit(app.exec_())



# from docx import Document
# from docx.shared import Inches
# from docx.enum.text import WD_ALIGN_PARAGRAPH
#
# document = Document()
#
#
# # document.add_heading('Document Title', 1)
# paragraph1 = document.add_paragraph()
# paragraph1.add_run('Изделие: ').bold =True
# paragraph1.add_run('СЭС-200М, ')
# paragraph1.add_run('зав.№: ').bold =True
# paragraph1.add_run('Н06001')
# paragraph1.alignment = WD_ALIGN_PARAGRAPH.CENTER
# paragraph2 = document.add_paragraph()
# paragraph2.add_run('Блок: ').bold =True
# paragraph2.add_run('БУ50, ТАКИ, ')
# paragraph2.add_run('зав.№: ').bold =True
# paragraph2.add_run('Н06001')
# paragraph2.alignment = WD_ALIGN_PARAGRAPH.CENTER
#
# p = document.add_paragraph('A plain paragraph having some ')
# p.add_run('bold').bold = True
# p.add_run(' and some ')
# p.add_run('italic.').italic = True
#
# document.add_heading('Heading, level 1', level=1)
# document.add_paragraph('Intense quote', style='Intense Quote')
#
# document.add_paragraph(
#     'first item in unordered list', style='List Bullet'
# )
# document.add_paragraph(
#     'first item in ordered list', style='List Number'
# )
#
# # document.add_picture('monty-truth.png', width=Inches(1.25))
#
# records = (
#     (3, '101', 'Spam'),
#     (7, '422', 'Eggs'),
#     (4, '631', 'Spam, spam, eggs, and spam')
# )
#
# table = document.add_table(rows=1, cols=3)
# hdr_cells = table.rows[0].cells
# hdr_cells[0].text = 'Qty'
# hdr_cells[1].text = 'Id'
# hdr_cells[2].text = 'Desc'
# for qty, id, desc in records:
#     row_cells = table.add_row().cells
#     row_cells[0].text = str(qty)
#     row_cells[1].text = id
#     row_cells[2].text = desc
#
# document.add_page_break()
#
# document.save('demo.docx')

# import json
# with open('configs.json','r') as file_configs:
#     configs = json.load(file_configs)
#     for i in configs.values():
#         if i in 'FT3A213':
#             print(i)
    # print(configs.values())

# flag_abort =0
# count = 0
# count2 =0
# data_can ='preset'
# mode = 'w'
# addr =0
# id = 1
# flag = 0
# data_dict = [10,20,30]
#
#
# for data_main in data_dict:
#     print('data_main',data_main)
#     # Запрос с адресом в can
#     while True:
#         if flag_abort == 1:
#             print('ABORT')
#         print('while_main')
#         count += 1
#         count2+=count+1
#         # Если парсятся уставки
#         if data_can == 'preset':
#             if count > 4: count = 0; break
#             if mode == 'w':
#                 print('mode1')
#                 # print(self.data_dict[data_can][data_main[0]][count2+1])
#                 # print(self.data_dict[data_can][data_main[0]])
#                 # msg_bytes = self.transformed_in_bytes(addr, self.write_id, self.data_dict[data_can] \
#                 #     [data_main[0]][count2 + 1])
#         elif data_can == 'filter':
#             if count > 2: count = 0; break
#             if mode == 'w':
#                 print('mode1')
#                 # msg_bytes = self.transformed_in_bytes(addr, self.write_id, self.data_dict[data_can] \
#                 #     [data_main[0]][count-1])
#         elif data_can == 'calibr':
#             if count > 1: count = 0; break
#             if mode == 'w':
#                 print('mode2')
#                 # msg_bytes = self.transformed_in_bytes(addr, self.write_id, self.data_dict[data_can] \
#                 #     [data_main[0]][count])
#
#         # printf(number)
#         if mode == 'r':
#             # msg_bytes = self.transformed_in_bytes(addr, self.read_id)
#             print('rrrr')
#         addr += 4
#         # print(msg_bytes)
#         # self.ser.ser.write(msg_bytes)
#         cnt_recept =0
#         # Чтение с can значение и адреса
#         while True:
#             cnt_recept+=1
#             # read_data = self.ser.ser.read(self.ser.buffer_receiv_main)
#             print(id,'---')
#             if cnt_recept>=10:
#                 print('er_recept')
#                 # self.ser.ser.write(msg_bytes)
#                 cnt_recept =0
#             if id ==1:
#             # if id in read_data and msg_bytes[5:13] in read_data:
#             #     list_read_data = read_data.split(b'\r')
#                 list_read_data = [1]
#                 for i in list_read_data:
#                     if i==id:
#                     # if i[:4] == id and len(i) > 21 and msg_bytes[5:13] in i:
#                         read_data = i
#                         print('read_data',read_data)
#
#                         # Конвертируем значения hex в dec
#                         if data_can == 'preset':
#                             # value_dec = self.transformed_hex_to_dec(value, data_main[1][1])
#                             # value, address = self.transformed_in_value_and_address(read_data,
#                             #                                                        data_main[1][1])
#                             print('preset_convert')
#                             if mode == 'w':
#                                 # value_write, address_write = self.transformed_in_value_and_address \
#                                 #     (msg_bytes, data_main[1][1])
#                                 print('mode_convert')
#                             else:
#                                 # Добавление вычитаных значений в главный словарь
#                                 self.data_dict[data_can][data_main[0]].append(value)
#                         elif data_can == 'calibr':
#                             # value_dec = self.transformed_hex_to_dec(value, 'float')
#                             # value, address = self.transformed_in_value_and_address(read_data, 'float')
#                             pass
#
#                             if mode == 'w':
#                                 # value_write, address_write = self.transformed_in_value_and_address \
#                                 #     (msg_bytes, 'float')
#                                 pass
#                             else:
#                                 # Добавление вычитаных значений в главный словарь
#                                 # self.data_dict[data_can][data_main[0]].append(value)
#                                 pass
#                         else:
#                             # value_dec = self.transformed_hex_to_dec(value, 'int')
#                             # value, address = self.transformed_in_value_and_address(read_data, 'int')
#                             pass
#                             if mode == 'w':
#                                 # value_write, address_write = self.transformed_in_value_and_address \
#                                 #     (msg_bytes, 'int')
#                                 pass
#                             else:
#                                 # Добавление вычитаных значений в главный словарь
#                                 # self.data_dict[data_can][data_main[0]].append(value)
#                                 pass
#                         # Если отправленное значение отличается от значения в квитанции, то
#                         # повторяем отправку
#                         # if value_write != value and count < 20: addr -= 4; count -= 1; count1 += 1
#
#                         print('mode_val',mode)
#                         # self.file_open.write(hex(address).encode('utf-8') + b'\t')
#                         # self.file_open.write(hex(value).encode('utf-8') + b'\n')
#
#                         # self.file_open.write(hex(value_dec).encode('utf-8') + b'\n')
#                         flag = 1
#                         break
#                 if flag == 1: flag = 0; break



from debug import *
#
# def func_val_to_hex_can(c):
#     printf(c)
#     c = int(c)
#     printf(c)
#     c = hex(c)[2:].upper()
#     printf(c)
#     if len(c) == 1:
#         printf(type(c),c)
#         c = '0' + c + "000000"
#         printf(c)
#     elif len(c) == 2:
#         c = c + "000000"
#     elif len(c) == 3:
#         c = c + "00000"
#     elif len(c) == 4:
#         c = c[len(c) - 2:] + "  " + \
#             c[len(c) - 4:len(c) - 2] + "0000"
#     elif len(c) == 6:
#         c = c[len(c) - 2:] + "  " + \
#             c[len(c) - 4:len(c) - 2] + "  " + c[len(c) - 6:len(c) - 4] + "00"
#     elif len(c) == 8:
#         c = c[len(c) - 2:] + "  " + \
#             c[len(c) - 4:len(c) - 2] + "  " + c[len(c) - 6:len(c) - 4] + "  " + c[len(c) - 8:len(c) - 6]
#     return c
#
# a = func_val_to_hex_can('800')
# print(a)
#
# c = 1000
# c = hex(c)[2:].upper()
# printf(c)
#
#
# def trans_neg_hex_to_dec(arg):
#     arg = '0x' + arg
#     arg = int(arg, 16)
#     t = bin(arg)
#     s = str.maketrans('01', '10')
#     s1 = t[2:].translate(s)
#     s2 = (int(s1, 2) + 1) * -1
#     # printf(s2+1)
#     return s2
# # d = trans_neg_hex_to_dec('-25')
# # s2 = (int(d,2)+1)* -1
# # print(int(d))
#
#
# def to_twos_complement_hex(n, bits=32):
#     if n >= 0:
#         return hex(n)
#     else:
#         # Вычисляем дополнительный код
#         return hex((1 << bits) + n)
#
# val = -255
# val_32 = to_twos_complement_hex(val, 32)
# print(f"-255 в 32-битном доп. коде: {val_32}")
# # Вывод: -255 в 32-битном доп. коде: -0xff
#
# # d = '-41.875099'
# d = '0.0209'
# print(float(d))
#
# import struct
#
# number = -12.375
#
# packed = struct.pack('>f', float(d))
# # Преобразование байтов в целое число
# integer_representation = int.from_bytes(packed, byteorder='big') # byteorder должен соответствовать порядку байтов в packed
# # print(f"Целочисленное представление: {integer_representation}")
# # Преобразование целого числа в шестнадцатеричную строку
# hex_string = hex(integer_representation)
# print(f"Шестнадцатеричная строка: {hex_string}")
#
# #05 32 00 00
# c = '30251235'
# # arg = hex(arg)[2:].upper()
# # arg = arg[6:8] + arg[4:6] + arg[2:4] + arg[0:2]
# # c = c[len(c) - 2:] + "  " + \
# #     c[len(c) - 4:len(c) - 2] + "  " + c[len(c) - 6:len(c) - 4] + "  " + c[len(c) - 8:len(c) - 6]
# # c = c[len(c) - 2:] + \
# #     c[len(c) - 3:len(c) - 2] + "00000"
# c = '4'
# #51 40 0D 03
# #1
# c = '0' + c + "000000"
# #2
# # c = c + "000000"
# #3
# # c = c[1:]+ '0'+c[:1] +'0000'
# #4
# # c = c[len(c) - 2:] +\
# #     c[len(c) - 4:len(c) - 2] + "0000"
# #5
# # c = c[-2:] +c[1:3]+'0'+c[:1] +'00'
# #6
# # c = c[len(c) - 2:] +c[len(c) - 4:len(c) - 2] +\
# #            c[len(c) - 6:len(c) - 4] + "00"
# #7
# # c = c[-2:] +c[3:5] +c[1:3]+'0'+ c[:1]
# #8
# # c = c[len(c) - 2:] + c[len(c) - 4:len(c) - 2] + \
# #     c[len(c) - 6:len(c) - 4] + c[len(c) - 8:len(c) - 6]
# printf(c)
# # arg = b't01488C00D4BF0D4300000D82'
# # value = arg[13:21]
# # printf(value)
# # value = value[6:8] + value[4:6] + value[2:4] + value[0:2]
# # printf(value)
#
# import binascii
# def transformed_in_value_and_address(arg, type, func=None):
#     lst_val = []
#     value = arg[13:21]
#     printf(value)
#     value = value[6:8] + value[4:6] + value[2:4] + value[0:2]
#     printf('val', value)
#     value = value.decode('utf-8')
#     printf(value)
#     if type == 'int' and func == 'header':
#         printf(value)
#         value = binascii.unhexlify(value)
#         printf(value)
#         value = int.from_bytes(value, 'big', signed=True)
#         printf(value)
#         # value = struct.unpack('!I', bytes.fromhex(value))
#         value = [bytearray(value.to_bytes(length=4, byteorder="little", signed=True))]
#     elif type == 'int':
#         printf(value)
#         value = struct.unpack('!I', bytes.fromhex(value))
#     elif type == '-int':
#         value = [trans_neg_hex_to_dec(value)]
#         printf('val1', value)
#         # value = struct.unpack('!I', bytes.fromhex(value))
#     else:
#         value = struct.unpack('!f', bytes.fromhex(value))
#         lst_val.append(round(value[0], 6))
#         value = lst_val.copy()
#     address = arg[5:13]
#     address = address[6:8] + address[4:6] + address[2:4] + address[0:2]
#     address = address.decode('utf-8')
#     address = struct.unpack('!I', bytes.fromhex(address))
#     return value[0], address[0]
#
# arg = b't01488C00D4BF00D430000E38'
# # arg = transformed_in_value_and_address(arg,'int')
# print(arg)
# # value =b't01488C00D4BF00D430000E38'
# # value = arg[13:21]
# # value = value[6:8] + value[4:6] + value[2:4] + value[0:2]
#
#
# # val= bytearray(b'\x04\x00\x00\x00')
# val = bytearray(b'ZZ\xa5\xa5')
# val = int.from_bytes(val, 'little', signed=False)
# printf(val, type(val))
# val = hex(val)[2:].upper()
# # val = 'A5A55A5A'
# # val = val[6:8] + val[4:6] + val[2:4] + val[0:2]
# printf(val)
# # val = int(val)
# # val = hex(val)[2:].upper()
# #1
# # val = '0' + val + "000000"
# #2
# # val = val + "000000"
# #3
# # val = val[1:]+ '0'+val[:1] +'0000'
# #8
# val = val[len(val) - 2:] + val[len(val) - 4:len(val) - 2] + \
#     val[len(val) - 6:len(val) - 4] + val[len(val) - 8:len(val) - 6]
# val = val.encode('utf-8') + b'0000'
# printf(val)
#
# a = '5A5AA5A5'
#
# def trans_str(metric,text):
#     flag = 0
#     printf(text,metric)
#     if metric >269:
#         text = list(text)
#         for i in range(0,len(text)):
#             printf(i)
#             if i*7>269:
#                 if text[i] != ' ':
#                     if flag==0:
#                         j = i
#                         flag=1
#                     if flag==1:
#                         while(True):
#                             j-=1
#                             if text[j]==' ':
#                                 text[j] = '\n'
#                                 break
#                         break
#                 elif text[i] == ' ':
#                     text[i] = '\n'
#                     break
#         text = ''.join(text)
#         printf(text)
#         return [text]
#     else: return [text]
#
# text = 'Время, оставшееся до технич. обслуживания ЭА, с'
# metric = 326
# trans_str(metric,text)


# from pathlib import Path
# from borb.pdf import Document, Page, PageLayout, SingleColumnLayout, Paragraph, PDF
#
# # Create an empty Document
# d: Document = Document()
#
# # Create an empty Page
# p: Page = Page()
# d.append_page(p)
#
# # Create a PageLayout
# l: PageLayout = SingleColumnLayout(p)
#
# # Add a Paragraph
# l.append_layout_element(Paragraph('Hello World!'))
#
# # Write the PDF
# PDF.write(what=d, where_to="assets/output.pdf")
#
#
# from reportlab.pdfgen.canvas import Canvas
# from reportlab.lib.pagesizes import A4
# from reportlab.pdfbase import pdfmetrics
# from reportlab.pdfbase.ttfonts import TTFont
# from reportlab.pdfgen.canvas import Canvas
# canvas = Canvas("hello.pdf",pagesize=A4)
# pdfmetrics.registerFont(TTFont('DejaVuSerif','DejaVuSerif.ttf'))
# canvas.setFont('DejaVuSerif', 32)
# canvas.drawString(72, 72, "Привет, World")
# canvas.save()
#
# # canvas = Canvas("hello.pdf", pagesize=(612.0, 792.0))
# # from reportlab.lib.units import inch, cm
# from reportlab.lib.pagesizes import A4
# canvas = Canvas("hello.pdf", pagesize=A4)
#
#
# from reportlab.lib.units import inch, cm
# canvas = Canvas("font-example.pdf", pagesize=A4)
# canvas.setFont("Times-Roman", 12)
# canvas.drawString(1 * inch, 10 * inch, "Times New Roman (12 pt)")
# canvas.save()
#
#
# from reportlab.platypus import SimpleDocTemplate, Table, Paragraph
# from reportlab.lib.styles import getSampleStyleSheet
#
# # 1. Подготовьте данные в виде списка списков
# data = [
#     ['Заголовок 1', 'Заголовок 2', 'Заголовок 3'],
#     ['Строка 1, столбец 1', 'Строка 1, столбец 2', 'Строка 1, столбец 3'],
#     ['Строка 2, столбец 1', 'Строка 2, столбец 2', 'Строка 2, столбец 3'],
# ]
#
# # 2. Создайте объект таблицы
# table = Table(data)
#
# # 3. Создайте объект для хранения элементов документа (Story)
# story = []
#
# # 4. Добавьте таблицу в Story (опционально, можно добавить стиль)
# story.append(table)
#
# # 5. Создайте объект документа PDF
# doc = SimpleDocTemplate("table_example.pdf")
#
# # 6. Постройте PDF-документ
# doc.build(story)
#
# print("PDF-документ 'table_example.pdf' создан успешно.")
#
# from reportlab.lib import colors
# from reportlab.lib.pagesizes import letter, inch,A4
# from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
# from reportlab.pdfbase import pdfmetrics
# from reportlab.pdfbase.ttfonts import TTFont
# from reportlab.lib.styles import ParagraphStyle
#
# doc = SimpleDocTemplate("simple_table_grid.pdf", pagesize=letter)
# # container for the 'Flowable' objects
# elements = []
# pdfmetrics.registerFont(TTFont('DejaVuSans','DejaVuSans.ttf'))
# style_cyrillic = ParagraphStyle(
#     name='CyrillicStyle',
#     fontName='DejaVuSans',
#     fontSize=12,
#     leading=14
# )
# data = [['Desig', 'Наименование', 'Значение'], ['AIR_TEMP_k', 'T воздуха в отсеке, °C', '1.0']]
# # data= [['000000', '01', '02', '03', '04'],
# #        ['10', '11', '12', '13', '14'],
# #        ['20', '21', '22', '23', '24'],
# #        ['30', '31', '32', '33', '34']]
# # t=Table(data,5*[0.5*inch], 4*[0.3*inch])
# table_data = []
# for row in data:
#     table_row = [Paragraph(text, style_cyrillic) for text in row]
#     table_data.append(table_row)
# t=Table(table_data)
# t.setStyle(TableStyle([('ALIGN',(1,1),(-1,-2),'RIGHT'),
#                        ('TEXTCOLOR',(1,1),(-2,-2),colors.red),
#                        ('VALIGN',(0,0),(0,-1),'TOP'),
#                        ('TEXTCOLOR',(0,0),(0,-1),colors.blue),
#                        ('ALIGN',(0,-1),(-1,-1),'CENTER'),
#                        ('VALIGN',(0,-1),(-1,-1),'MIDDLE'),
#                        ('TEXTCOLOR',(0,-1),(-1,-1),colors.green),
#                        ('INNERGRID', (0,0), (-1,-1), 0.25, colors.black),
#                        ('BOX', (0,0), (-1,-1), 0.25, colors.black),
#                        ]))
#
# elements.append(t)
# # write the document to disk
# doc.build(elements)
#
#
#
# from reportlab.platypus import SimpleDocTemplate, TableStyle, Table
#
# # Creating a simple pdfdoc = SimpleDocTemplate(aa)
# story = []
#
# doc = SimpleDocTemplate("test1.pdf", pagesize=letter)
# # Set a table style
# table_style = TableStyle(
#     [
#         ('INNERGRID', (0,0), (-1,-1), 0.25, colors.black),
#         ('BOX', (0,0), (-1,-1), 0.25, colors.black),
#     ]
# )
#
# # Creating mock data and cols to add a new table inside the third a row
# data_table = [
#     ['Col1', 'Col2'],
#     ['aaa', 'bbb'],
#     [Table([['data to add as third row', 'a']], style=table_style)]
# ]
#
#
# final_table = Table(data_table, style=table_style)
# story.append(final_table)
# doc.build(story)

# import os,sys
# dir_name = os.path.dirname(__file__)
# printf(dir_name)
# dirs = sys.exec_prefix
# dirs_all = sys.executable
#
# folder = 'dif'
# printf(dirs_all)
# # dirs_all +=f"\{folder}"
# # printf(dirs_all)
# # dirs_all +=folder
# printf(dirs_all)
#
# out_file = 'test2.docx'
# input_dir = 'D:\repo\calibrator\prj2\csv,docx,pdf'
# def trans_path(dir,out_file,folder):
#     inp = ''
#     cnt =0
#     printf(dir.count('\\'))
#     for i in dir:
#         # print(i)
#         if cnt==dir.count('\\'):break
#         if i =='\r':
#             i ='\/\\r'
#         inp +=i
#         if i =='\\':
#             inp +='\\'
#             cnt+=1
#     printf(inp)
#     # inp += f'\/\\{out_file}'
#     # inp = inp.replace('/','')
#     inp +=f'{folder}\\\{out_file}'
#     return inp
#
# # temp =trans_path(dirs_all,out_file,folder)
# # printf(temp)
#
# import os
#
# current_file = os.path.realpath(__file__)
# current_directory = os.path.dirname(current_file)
# printf(current_file)
# printf(current_directory)
# printf(os.path.abspath(__file__))
# printf(dirs_all)
#
# printf(dirs_all.count('\\'))

# import subprocess
#
# try:
#     # Запускаем команду `where soffice.exe`
#     # capture_output=True захватывает вывод команды
#     # text=True декодирует вывод в строку
#     result = subprocess.run(['where', 'soffice.exe'], capture_output=True, text=True, check=True)
#     # Вывод `where` может содержать несколько путей, разделенных переносом строки.
#     # Берем первый путь, обычно это основной путь к исполняемому файлу.
#     soffice_path = result.stdout.strip().split('\n')[0]
#     print(f"Путь к soffice.exe: {soffice_path}")
# except FileNotFoundError:
#     print("Команда 'where' не найдена. Убедитесь, что система Windows доступна для запуска команды.")
# except subprocess.CalledProcessError as e:
#     print(f"Ошибка при поиске soffice.exe: {e.stderr}")
#     print("Возможно, soffice.exe отсутствует в переменной PATH или не установлен.")

# from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle
# from reportlab.lib.styles import getSampleStyleSheet
# from reportlab.lib import colors
#
# # 1. Создаем документ и стили
# doc = SimpleDocTemplate("table_with_title.pdf")
# styles = getSampleStyleSheet()
# story = []
#
# # 2. Создаем текст заголовка
# title_text = "Hello"
# title_style = styles['h1'] # Или любой другой стиль
# title_paragraph = Paragraph(title_text, title_style)
# story.append(title_paragraph)
#
# # 3. Подготавливаем данные для таблицы
# data = [
#     ["Столбец 1", "Столбец 2", "Столбец 3"],
#     ["Ячейка A1", "Ячейка B1", "Ячейка C1"],
#     ["Ячейка A2", "Ячейка B2", "Ячейка C2"]
# ]
#
# # 4. Создаем саму таблицу
# table = Table(data)
#
# # 5. Добавляем стили к таблице (например, цвета фона для заголовка)
# style = TableStyle([
#     ('BACKGROUND', (0, 0), (-1, 0), colors.grey), # Цвет фона для заголовка
#     ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
#     ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
#     ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
#     ('FONTSIZE', (0, 0), (-1, 0), 14),
#     ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
#     ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
#     ('GRID', (0, 0), (-1, -1), 1, colors.black)
# ])
# table.setStyle(style)
# story.append(table)
#
# # 6. Собираем документ (сохраняем PDF)
# doc.build(story)
#
#
# from reportlab.platypus import SimpleDocTemplate, Paragraph
# from reportlab.lib.styles import getSampleStyleSheet
# doc = SimpleDocTemplate("bold_example.pdf") # Создаем PDF-документ
# styles = getSampleStyleSheet() # Получаем стандартные стили
# pdfmetrics.registerFont(TTFont('TimesNewRomanCyrillic', 'timesnrcyrmt.ttf'))
# # СоздаемParagraph, в тексте которого есть тег <b>
# # <b> - это стандартный HTML-тег для жирного текста.
# text_with_bold = Paragraph("Hello <b>World</b>.", styles['Normal'])
# # Добавляем наш Paragraph в список элементов для документа
# story = [text_with_bold]
# # Собираем документ
# doc.build(story)
#
#
# from reportlab.platypus import SimpleDocTemplate, Paragraph
# from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
# from reportlab.pdfbase import pdfmetrics
# from reportlab.pdfbase.ttfonts import TTFont
# import os
#
# pdfmetrics.registerFont(TTFont('Times-Bold-Cyrillic', 'timesnrcyrmt.ttf')) # Регистрируем шрифт
# doc = SimpleDocTemplate("bold_cyrillic_example.pdf")
# styles = getSampleStyleSheet()
# # Создаем стиль с жирным кириллическим шрифтом
# bold_cyrillic_style = ParagraphStyle(
#     name='BoldCyrillic',
#     fontName='Times-Bold-Cyrillic',
#     fontSize=14,
#     leading=16
# )
# story = []
# # Используем жирный шрифт для всего текста параграфа
# story.append(Paragraph('<b>Этот текст будет</b> жирным', bold_cyrillic_style))
# story.append(Paragraph('<b><font name="Times-Bold-Cyrillic">Этот тоже будет жирным</font></b>', bold_cyrillic_style))
#
#
# doc.build(story)
#
# from reportlab.platypus import SimpleDocTemplate, Paragraph
# from reportlab.lib.styles import getSampleStyleSheet
# from reportlab.lib.units import inch
# from reportlab.pdfbase import pdfmetrics
#
# pdfmetrics.registerFont(TTFont('Times-Bold-Cyrillic', 'timesnrcyrmt_bold.ttf')) # Регистрируем шрифт
# # 1. Создаем объект документа
# doc = SimpleDocTemplate("styled_text_example.pdf")
# # 2. Получаем стандартные стили
# styles = getSampleStyleSheet()
# # 3. Определяем текст с RML-тегами для форматирования
# text_with_styles = """
# Это <b>жирный</b> текст.
# Это <i>курсивный</i> текст.
# Это текст с другим <font name="Times-Bold-Cyrillic" size="14" ><b>шрифтом</b></font>.
# Можно также комбинировать стили: <b><i>жирный и курсивный</i></b>.
# """
# # 4. Создаем объект Paragraph с применением стилей
# # styles['Normal'] - это базовый стиль, в который встраиваются RML-теги
# paragraph = Paragraph(text_with_styles, styles['Normal'])
# # 5. Собираем элементы документа
# story = []
# story.append(paragraph)
# # 6. Создаем PDF-документ
# doc.build(story)
#
#
# from reportlab.pdfbase import pdfmetrics
# from reportlab.pdfbase.ttfonts import TTFont
# from reportlab.platypus import SimpleDocTemplate, Paragraph
# from reportlab.lib.styles import getSampleStyleSheet
#
# # Зарегистрируйте свой собственный шрифт
# pdfmetrics.registerFont(TTFont('MyCustomFont', 'timesnrcyrmt.ttf'))
# doc = SimpleDocTemplate("report_with_custom_font.pdf")
# styles = getSampleStyleSheet()
# # Создайте стиль, используя ваш собственный шрифт
# custom_style = styles['Normal']
# custom_style.fontName = 'MyCustomFont'
# # Используйте теги внутри параграфа
# text = '<font name="MyCustomFont">Этот текст будет использовать<br/> <b>мой шрифт</b>.</font>'
# p = Paragraph(text, custom_style)
# story = [p]
# doc.build(story)
#
# from reportlab.pdfgen import canvas
# pdfmetrics.registerFont(TTFont('MyCustomFont', 'timesnrcyrmt.ttf'))
# pdfmetrics.registerFont(TTFont('MyCustomFontBold', 'timesnrcyrmt_bold.ttf'))
# # Создаем объект canvas
# c = canvas.Canvas("new_line_example.pdf")
# c.setFont('MyCustomFont',12)
# # Добавляем первый текст
# text1 = "Это первая строка"
# c.drawString(100, 750, text1)
# c.setFont('MyCustomFontBold',12)
# # Добавляем перенос строки и второй текст
# text2 = "Это вторая строка, добавленная с помощью \\n"
# c.drawString(200, 750, text2)
# # Сохраняем PDF
# c.save()
#
#
# from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer,BaseDocTemplate
# from reportlab.lib.styles import getSampleStyleSheet
# from reportlab.platypus.doctemplate import PageTemplate
# from reportlab.pdfgen import canvas as pdfcanvas
#
# pdfmetrics.registerFont(TTFont('MyCustomFont', 'timesnrcyrmt.ttf'))
# def footer(canvas, doc):
#     canvas.saveState()
#     canvas.setFont('MyCustomFont', 9)
#     canvas.drawString(100, 60, "Это мой нижний колонтитул")
#     canvas.restoreState()
#
# # Предположим, у нас уже есть объект doc, созданный из SimpleDocTemplate
# doc = BaseDocTemplate("document_with_canvas.pdf")
#
# # Создаем стандартный template (вместо добавления к нему canvas)
# story = []
# styles = getSampleStyleSheet()
# story.append(Paragraph("Пример документа", styles['h1']))
# story.append(Spacer(1, 0.2*72)) # 0.2 дюйма
# for i in range(20):
#     story.append(Paragraph("Пример строки текста", styles['Normal']))
#     story.append(Spacer(1, 0.1*72))
#
# # Создаем новую страницу и добавляем колонтитул
# doc.addPageTemplates([PageTemplate(id='OneCol', frames=[doc.frame], onPage=footer)])
# doc.build(story)

#
# import subprocess
#
# user = subprocess.run(['whoami'], capture_output=True, text=True)
# subprocess.run(['chown', '-R', user, ':users', '/dev'], capture_output=True, text=True)

# from PyQt5.QtSerialPort import QSerialPort,QSerialPortInfo
# from PyQt5.QtCore import QIODevice
# for port_info in QSerialPortInfo.availablePorts():
#     # print(f"Port Name: {port_info.portName()}, Description: {port_info.description()}")
#     print(port_info.manufacturer(),port_info.hasProductIdentifier(),port_info.hasVendorIdentifier(),port_info.productIdentifier(),\
#           port_info.systemLocation(),port_info.serialNumber(),port_info.vendorIdentifier())
#
# import serial.tools.list_ports
# import serial
#
# # print(serial.serialwin32.SerialBase.port.fget())
# ports = serial.tools.list_ports.comports()
# for port in ports:
#     printf(port.hwid, port.name, port.vid, port.pid, port.serial_number, port.location, port.manufacturer, port.product,
#            port.interface)
#
# import winreg
# import itertools
#
# def serial_ports() -> list:
#     path = 'HARDWARE\\DEVICEMAP\\SERIALCOMM'
#     key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, path)
#
#     ports = []
#     for i in itertools.count():
#         try:
#             ports.append(winreg.EnumValue(key, i)[1])
#         except EnvironmentError:
#             break
#
#     return ports
#
# printf(serial_ports())
#
#
# def get_serial_number_from_registry(key_path, param_name):
#     try:
#         # Открываем ключ реестра
#         key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, key_path, 0, winreg.KEY_READ)
#
#         # Получаем значение параметра
#         value, reg_type = winreg.QueryValueEx(key, param_name)
#         printf(reg_type)
#
#         # Закрываем ключ
#         winreg.CloseKey(key)
#
#         return value
#     except FileNotFoundError:
#         print(f"Ключ или параметр не найден: {key_path}\\{param_name}")
#         return None
#     except Exception as e:
#         print(f"Ошибка при чтении реестра: {e}")
#         return None
#
# # Пример использования (замените путь и имя параметра на реальные)
# key_path = r"SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion"
# param_name = "ProductID"
# serial = get_serial_number_from_registry(key_path, param_name)
# if serial:
#     print(f"Серийный номер: {serial}")

# from class_read_data import Calibrator
lst_read = [
            [b't64081C40D4BF00000DA060D8\rt0348647D00000000E00360E3\rt03484C8100000000000060E4\rt03484C8100000000000060E4\rt03184C8100000000000060E5\rt0318647D00000000E00360E5\rt0318982F0000020000EA60E6\rt0328936E0000480A000060EE\rt03289D2F00000000000060EE\rt03288C2F00000000000060EF\rt02F84B2F00000000100060EF\rt02F82F0100000100000060F0\rt02F8902F00000000000060F0\rt02F8330000000000000060F1\rt02F84A2F0000A4AA8E0060F1\rt02F88C2F00000000000060F2\rt03C829460F000000000060FE\r'],
            [b't0338DD07000000000000610F\rz\rt0338DE07000000000000610F\rt03388C130000000000006110\rt03388D130000000000006110\rt033895130000000000006111\rt0338DF070000000000006111\rt03388E130000000000006112\rt03D8114A0F0002ABD6416112\rt64082040D4BF040000006118\r'],
            [b't0348647D00000000E003614A\rt03484C81000000000000614A\rt03484C81000000000000614B\rt03184C81000000000000614B\rt0318647D00000000E003614C\rt0318982F0000020000EA614C\rz\rt0328936E0000480A00006152\rt03289D2F0000000000006152\r'],
            [b't033896130000000000006173\rt033897130000000000006174\rt0338C7D80100080100006174\rt033836230000000000006175\rt033855240000000000006175\rt033857240000000000006176\rt03384C2F0000030025096176\rt0308C7D80100080100006177\rt030801810000000000006177\rt033835230000000000006178\rt033837230000000000006178\rt033856240000000000006179\rt0338E22E0000ECCEAD006179\rt0308197D000000000000617A\rt0308EE2E000002000000617A\r'],
            [b't0348647D00000000E00361AC\rt03484C8100000000000061AC\rt03484C8100000000000061AC\rt03184C8100000000000061AD\rt0318647D00000000E00361AD\rt0318982F0000020000EA61AE\rt03288C2F00000000000061B6\rt02F8330000000000000061B6\rt02F84A2F0000A4AA8E0061B7\rt02F88C2F00000000000061B7\rt64082840D4BF0400000061B8\rt02F84B2F00000000100061B8\rt02F82F0100000100000061B9\rt02F8902F00000000000061B9\r'],
            [b't0348647D00000000E0030A8C\rt03484C810000000000000A8D\rt03484C810000000000000A8D\rt03184C810000000000000A8E\rt0318647D00000000E0030A8E\rt0318982F0000020000EA0A8F\rt0328E12E0000887700000A96\rt0328F22E00000000D0BF0A97\rt0328EF2E00004C7304A00A97\rt03289D2F0000000000000A98\rt02F833000000000000000A98\rt02F84A2F0000A4AA8E000A99\rt02F88C2F0000000000000A99\rt0328936E0000480A00000A9A\rt03288C2F0000000000000A9A\rt02F84B2F0000000010000A9B\rt02F82F010000010000000A9B\rt02F8902F0000000000000A9C\r'],
            [b't0338027D0000000000000AB9\rt0338037D0000000000000AB9\rt0338047D0000000000000ABA\rt0338067D0000000000000ABA\rt03383D7E0000000000000ABB\rt0338EA800000000000000ABB\rt0338EC800000000000000ABC\rt0338EE800000000000000ABC\rt033820820000000000000ABD\rt03385C760000010000000ABD\rt033839230000000000000ABE\rt0308A2130000020000000ABE\rt0308C7D80100080100000ABF\rt0338057D0000000000000ABF\rt03383B7E0000000000000AC0\rt03383C7E0000000000000AC0\rt0338E9800000000000000AC1\rt0338EB800000000000000AC1\rt0338ED800000000000000AC2\rt03381F820000000000000AC2\rt033821820000000000000AC3\rt0338447A0000010000000AC3\rt0308A5130000B401B5410AC4\rt03084D2F00000800000C0AC4\rt0308197D0000000000000AC5\r'],
            [b't03484C810000000000000B54\rt03484C810000000000000B55\rt0318647D00000000E0030B55\rt0318982F0000020000EA0B56\rt03184C810000000000000B56\rt03281F300000AC0000000B5F\rt032820300000AD0000000B5F\rt0328E12E0000507800000B60\rt032830300000B10000000B60\rt032832300000B30000000B61\rt032834300000B50000000B61\rt032842300000B70000000B61\rt032844300000B90000000B62\rt032846300000BB0000000B62\rt03281252000001C0BB410B63\rt032833000000000000000B63\rt032854300000000000000B64\rt0328114A0F005F87D5410B64\rt032822300000AF0000000B65\rt03282F300000B00000000B65\rt032831300000B20000000B66\rt032833300000B40000000B66\rt032841300000B60000000B67\rt032843300000B80000000B67\rt032845300000BA0000000B68\rt03280A5200003600BC410B68\rt032834530000000000000B69\rt032853300000000000000B69\rt0328936E0000480A00000B6A\rt0328104A0F00000000000B6A\r'],
            [b't0338D40700009C18CD430B80\rt0338D507000033A8CD430B81\rt0338D6070000AAC2CD430B81\rt0338D8070000333348420B81\rt0338E3070000000000000B82\rt0338E5070000000000000B82\rt0338DE070000000000000B83\rt0338DA070000C10000000B83\rt0338DC070000480000000B84\rt0338D7070000333348420B84\rt0338D9070000CDCC47420B85\rt0338E4070000000000000B85\rt0338DD070000000000000B86\rt0338DF070000000000000B86\rt0338DB070000380100000B87\rt0338E60700000000803F0B87\r'],
            [b't0348647D00000000E0030BB9\rt03484C810000000000000BB9\rt03484C810000000000000BBA\rt03184C810000000000000BBA\rt0318647D00000000E0030BBB\rt0318982F0000020000EA0BBB\rt0328EC5E0000010000000BC2\rt0328D4620000010000000BC3\rt0328BC660000010000000BC3\rt032810520000000000000BC4\rt0328455300004B0C00000BC4\rt02F833000000000000000BC5\rt03288C2F0000000000000BC5\rt02F82F010000010000000BC6\rt02F8902F0000000000000BC6\rt01481C00D4BF010000000BC7\rt0328A46A0000010000000BC7\rt03289D2F0000000000000BC7\rt032846530000490C00000BC8\rt03285B300000000000EA0BC8\rt02F84B2F0000000010000BC9\rt02F84A2F0000A4AA8E000BC9\rt02F88C2F0000000000000BCA\rt02F85B300000000000EA0BCA\r'],
            [b't0338E8070000000000000BE6\rt0338E9070000000000000BE6\rt0338BF0B0000000000000BE7\rt03388D130000000000000BE7\rt03388F130000000000000BE8\rt033895130000000000000BE8\rt033897130000000000000BE9\rt0338E22E00003CE3AD000BE9\rt03384C2F0000030025090BEA\rt033838230000000000000BEA\rt0308197D0000000000000BEB\rt0308EE2E0000020000000BEB\rt03388C130000000000000BEC\rt03388E130000000000000BEC\rt0338A6130000000000000BED\rt033896130000000000000BED\rt0338C7D80100080100000BEE\rt0308C7D80100080100000BEE\rt030801810000000000000BEF\r'],
            [b't03480B2F0000C8D305A00C1D\rt0348472F00000040D4BF0C1E\rt0348F32E00000000D0BF0C1E\rt0348647D00000000E0030C1F\rt03484C810000000000000C1F\rt0318647D00000000E0030C20\rt0318982F0000020000EA0C20\rt0348152F00000020D4BF0C20\rt03483D2F0000D0D405A00C21\rt0348F02E0000B83705A00C21\rt03484C810000000000000C22\rt03184C810000000000000C22\rt0328936E0000480A00000C27\rt03289D2F0000000000000C28\rt03288C2F0000000000000C28\rt02F84B2F0000000010000C29\rt02F82F010000010000000C29\rt02F833000000000000000C2A\rt02F84A2F0000A4AA8E000C2A\rt03C829460F00000000000C37\r'],
            ]

for i in lst_read:
    if b't0348' in i[0]:
        list_read = i[0].split(b'\r')
        for j in list_read:
            printf(j)
# for i in lst_read:
#     if b'647D0000' in i:
#         list_read_data = i.split(b'\r')
#         for j in list_read_data:
#             if b'647D0000' in j:
#                 printf(j)
#                 val,adr = Calibrator.transformed_in_value_and_address(Calibrator,j,'int')
#                 printf(val)

with open('lst.txt') as f_lst:
    a = f_lst.readlines()
    printf(a)
    # a=a.split(',')
    # if '32' in a:
    #     printf(a)

# from data_key2 import func_val_to_hex_can_flip
# val = 32100
# val = 40000012
# # val = hex(val)[2:].upper()
# # printf(val)
# val = func_val_to_hex_can_flip(val)
# printf(val)
#
# text = 'AIR_TEMP '
# if 'AIR_TEMP ' in text:
#     printf('YES')
#
# with open('data_key2.txt') as f_data_key:
#     read = f_data_key.readlines()
#     for i in read:
#         if 'KEY_'+"AIR_TEMP " in i:
#             lst_i = i.split(' ')
#     printf(lst_i)
#     # for i in read:
#     #     printf(i)
