# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout
# from PyQt5.QtCore import QCoreApplication
# import time
#
# class MyWindow(QWidget):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle("Process Events Example")
#         self.setGeometry(100, 100, 300, 200)
#
#         layout = QVBoxLayout()
#         self.button = QPushButton("Start Long Operation")
#         self.button.clicked.connect(self.start_long_operation)
#         layout.addWidget(self.button)
#         self.setLayout(layout)
#
#     def start_long_operation(self):
#         print("Starting long operation...")
#         for i in range(10):
#             print(f"Processing step {i+1}...")
#             time.sleep(0.5)  # Simulate a long-running task
#             QCoreApplication.processEvents() # Process events to keep UI responsive
#         print("Long operation finished.")
#
# if __name__ == "__main__":
#     app = QApplication([])
#     window = MyWindow()
#     window.show()
#     app.exec_()

# from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QTextEdit
# import sys
#
#
# class MyApp(QWidget):
#     def __init__(self):
#         super().__init__()
#         self.setWindowTitle("Ввод текста PyQt5")
#         self.setGeometry(100, 100, 300, 200)
#
#         # Создаем виджет QTextEdit
#         self.text_input = QTextEdit(self)
#         self.text_input.setPlaceholderText("Введите текст здесь...")  # Установка текста-подсказки
#         self.text_input.textChanged.connect(self.on_text_changed)  # Подключение сигнала изменения текста
#
#         # Создаем компоновщик и добавляем виджеты
#         layout = QVBoxLayout()
#         layout.addWidget(self.text_input)
#         self.setLayout(layout)
#         return None
#
#     def on_text_changed(self):
#         # Получаем текущий текст из виджета
#         current_text = self.text_input.toPlainText()
#         print(f"Введенный текст: {current_text}")
# if __name__ == '__main__':
#     app = QApplication(sys.argv)
#     window = MyApp()
#     print(window)
#     window.show()
#     sys.exit(app.exec_())



# from docx import Document
# from docx.shared import Inches
# from docx.enum.text import WD_ALIGN_PARAGRAPH
#
# document = Document()
#
#
# # document.add_heading('Document Title', 1)
# paragraph1 = document.add_paragraph()
# paragraph1.add_run('Изделие: ').bold =True
# paragraph1.add_run('СЭС-200М, ')
# paragraph1.add_run('зав.№: ').bold =True
# paragraph1.add_run('Н06001')
# paragraph1.alignment = WD_ALIGN_PARAGRAPH.CENTER
# paragraph2 = document.add_paragraph()
# paragraph2.add_run('Блок: ').bold =True
# paragraph2.add_run('БУ50, ТАКИ, ')
# paragraph2.add_run('зав.№: ').bold =True
# paragraph2.add_run('Н06001')
# paragraph2.alignment = WD_ALIGN_PARAGRAPH.CENTER
#
# p = document.add_paragraph('A plain paragraph having some ')
# p.add_run('bold').bold = True
# p.add_run(' and some ')
# p.add_run('italic.').italic = True
#
# document.add_heading('Heading, level 1', level=1)
# document.add_paragraph('Intense quote', style='Intense Quote')
#
# document.add_paragraph(
#     'first item in unordered list', style='List Bullet'
# )
# document.add_paragraph(
#     'first item in ordered list', style='List Number'
# )
#
# # document.add_picture('monty-truth.png', width=Inches(1.25))
#
# records = (
#     (3, '101', 'Spam'),
#     (7, '422', 'Eggs'),
#     (4, '631', 'Spam, spam, eggs, and spam')
# )
#
# table = document.add_table(rows=1, cols=3)
# hdr_cells = table.rows[0].cells
# hdr_cells[0].text = 'Qty'
# hdr_cells[1].text = 'Id'
# hdr_cells[2].text = 'Desc'
# for qty, id, desc in records:
#     row_cells = table.add_row().cells
#     row_cells[0].text = str(qty)
#     row_cells[1].text = id
#     row_cells[2].text = desc
#
# document.add_page_break()
#
# document.save('demo.docx')

# import json
# with open('configs.json','r') as file_configs:
#     configs = json.load(file_configs)
#     for i in configs.values():
#         if i in 'FT3A213':
#             print(i)
    # print(configs.values())

flag_abort =0
count = 0
count2 =0
data_can ='preset'
mode = 'w'
addr =0
id = 1
flag = 0
data_dict = [10,20,30]


for data_main in data_dict:
    print('data_main',data_main)
    # Запрос с адресом в can
    while True:
        if flag_abort == 1:
            print('ABORT')
        print('while_main')
        count += 1
        count2+=count+1
        # Если парсятся уставки
        if data_can == 'preset':
            if count > 4: count = 0; break
            if mode == 'w':
                print('mode1')
                # print(self.data_dict[data_can][data_main[0]][count2+1])
                # print(self.data_dict[data_can][data_main[0]])
                # msg_bytes = self.transformed_in_bytes(addr, self.write_id, self.data_dict[data_can] \
                #     [data_main[0]][count2 + 1])
        elif data_can == 'filter':
            if count > 2: count = 0; break
            if mode == 'w':
                print('mode1')
                # msg_bytes = self.transformed_in_bytes(addr, self.write_id, self.data_dict[data_can] \
                #     [data_main[0]][count-1])
        elif data_can == 'calibr':
            if count > 1: count = 0; break
            if mode == 'w':
                print('mode2')
                # msg_bytes = self.transformed_in_bytes(addr, self.write_id, self.data_dict[data_can] \
                #     [data_main[0]][count])

        # printf(number)
        if mode == 'r':
            # msg_bytes = self.transformed_in_bytes(addr, self.read_id)
            print('rrrr')
        addr += 4
        # print(msg_bytes)
        # self.ser.ser.write(msg_bytes)
        cnt_recept =0
        # Чтение с can значение и адреса
        while True:
            cnt_recept+=1
            # read_data = self.ser.ser.read(self.ser.buffer_receiv_main)
            print(id,'---')
            if cnt_recept>=10:
                print('er_recept')
                # self.ser.ser.write(msg_bytes)
                cnt_recept =0
            if id ==1:
            # if id in read_data and msg_bytes[5:13] in read_data:
            #     list_read_data = read_data.split(b'\r')
                list_read_data = [1]
                for i in list_read_data:
                    if i==id:
                    # if i[:4] == id and len(i) > 21 and msg_bytes[5:13] in i:
                        read_data = i
                        print('read_data',read_data)

                        # Конвертируем значения hex в dec
                        if data_can == 'preset':
                            # value_dec = self.transformed_hex_to_dec(value, data_main[1][1])
                            # value, address = self.transformed_in_value_and_address(read_data,
                            #                                                        data_main[1][1])
                            print('preset_convert')
                            if mode == 'w':
                                # value_write, address_write = self.transformed_in_value_and_address \
                                #     (msg_bytes, data_main[1][1])
                                print('mode_convert')
                            else:
                                # Добавление вычитаных значений в главный словарь
                                self.data_dict[data_can][data_main[0]].append(value)
                        elif data_can == 'calibr':
                            # value_dec = self.transformed_hex_to_dec(value, 'float')
                            # value, address = self.transformed_in_value_and_address(read_data, 'float')
                            pass

                            if mode == 'w':
                                # value_write, address_write = self.transformed_in_value_and_address \
                                #     (msg_bytes, 'float')
                                pass
                            else:
                                # Добавление вычитаных значений в главный словарь
                                # self.data_dict[data_can][data_main[0]].append(value)
                                pass
                        else:
                            # value_dec = self.transformed_hex_to_dec(value, 'int')
                            # value, address = self.transformed_in_value_and_address(read_data, 'int')
                            pass
                            if mode == 'w':
                                # value_write, address_write = self.transformed_in_value_and_address \
                                #     (msg_bytes, 'int')
                                pass
                            else:
                                # Добавление вычитаных значений в главный словарь
                                # self.data_dict[data_can][data_main[0]].append(value)
                                pass
                        # Если отправленное значение отличается от значения в квитанции, то
                        # повторяем отправку
                        # if value_write != value and count < 20: addr -= 4; count -= 1; count1 += 1

                        print('mode_val',mode)
                        # self.file_open.write(hex(address).encode('utf-8') + b'\t')
                        # self.file_open.write(hex(value).encode('utf-8') + b'\n')

                        # self.file_open.write(hex(value_dec).encode('utf-8') + b'\n')
                        flag = 1
                        break
                if flag == 1: flag = 0; break
