# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QApplication, QWidget, QPushButton, QVBoxLayout
from PyQt5.QtCore import QCoreApplication
import time

class MyWindow(QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Process Events Example")
        self.setGeometry(100, 100, 300, 200)

        layout = QVBoxLayout()
        self.button = QPushButton("Start Long Operation")
        self.button.clicked.connect(self.start_long_operation)
        layout.addWidget(self.button)
        self.setLayout(layout)

    def start_long_operation(self):
        print("Starting long operation...")
        for i in range(10):
            print(f"Processing step {i+1}...")
            time.sleep(0.5)  # Simulate a long-running task
            QCoreApplication.processEvents() # Process events to keep UI responsive
        print("Long operation finished.")

if __name__ == "__main__":
    app = QApplication([])
    window = MyWindow()
    window.show()
    app.exec_()