# Generated by Django 4.0.1 on 2023-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(blank=True, null=True, upload_to='articles'),
        ),
    ]
